language: android
sudo: required
jdk:
  - openjdk8
  - openjdk11
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - android-25
env:
  - ANDROID_HOME=/usr/local/android-sdk
before_script:
  - wget https://services.gradle.org/distributions/gradle-5.6.4-all.zip
  - unzip gradle-5.6.4-all.zip > /dev/null
  - export GRADLE_HOME=$PWD/gradle-5.6.4
  - export PATH=$GRADLE_HOME/bin:$PATH
  - . $HOME/.nvm/nvm.sh
  - nvm install 10
  - nvm use 10
  - npm i
script:
  - npm run lint
  - npm run test
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
