language: android
sudo: required
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    - android-25
env:
  - ANDROID_HOME=/usr/local/android-sdk
before_script:
    - wget http://services.gradle.org/distributions/gradle-5.2-bin.zip
    - unzip gradle-5.2-bin.zip
    - export GRADLE_HOME=$PWD/gradle-5.2
    - export PATH=$GRADLE_HOME/bin:$PATH
    - . $HOME/.nvm/nvm.sh
    - nvm install 6
    - nvm use 6
    - npm install
script:
  - make travis
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
